# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               mojeproblemy
tagline:             '.suki.wtf'
description:         'Moje problémy. Krásně zaverzované'
url:                 http://mojeproblemy.suki.wtf
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jakub Boukal
  url:               https://github.com/SukiCZ
  email:             www.bagr@gmail.com

# Custom vars
version:             1.0.0
gems:                [jekyll-paginate]